# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='person',
            new_name='profile',
        ),
    ]
